server:
  port: 8443
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /jeecg-boot
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
iot:
  websocket:
    port: 8081