server:
  port: 8443
  tomcat:
    max-swallow-size: -1
  servlet:
    context-path: /pushServer
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
management:
  endpoints:
    web:
      exposure:
        include: metrics,httptrace
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
    #json 时间戳统一转换
  jackson:
    date-format:   yyyy-MM-dd HH:mm:ss
    time-zone:   GMT+8
  mvc:
    static-path-pattern: /**
    resource:
      static-locations: classpath:/static/,classpath:/public/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

iot:
  websocket:
    port: 8081